---
  all:
    hosts:
      ansibletest03:
        ansible_host: 192.168.1.3
        iface: ens161
        ksurl: https://raw.githubusercontent.com/Sapphire-Health/ansible-vmware-build/master/kickstarts/rhel8.ks
        extra_kernel_args: inst.noverifyssl
        disks:
          - size_gb: 120
            type: thick
            datastore: VCENTER_DATASTORE
            controller_number: 0
            unit_number: 0
            controller_type: paravirtual
          - size_gb: 20
            type: thick
            datastore: VCENTER_DATASTORE
            controller_number: 0
            unit_number: 1
            controller_type: paravirtual
          - size_gb: 30
            type: thick
            datastore: VCENTER_DATASTORE
            controller_number: 1
            unit_number: 0
            controller_type: paravirtual
          - size_gb: 146
            type: thick
            datastore: VCENTER_DATASTORE
            controller_number: 2
            unit_number: 0
            controller_type: paravirtual
          - size_gb: 60
            type: thick
            datastore: VCENTER_DATASTORE
            controller_number: 3
            unit_number: 0
            controller_type: paravirtual
      ansibletest04:
        ansible_host: 192.168.1.4
        num_cpus: 2
        memory_mb: 4096
        ksurl: https://raw.githubusercontent.com/Sapphire-Health/ansible-vmware-build/master/kickstarts/rhel8.ks
        extra_kernel_args: inst.noverifyssl
        disks:
          - size_gb: 25
            type: thick
            datastore: VCENTER_DATASTORE
            controller_number: 0
            unit_number: 0
            controller_type: paravirtual
    vars:
      build: rhel8
      memory_mb: 2048
      num_cpus: 1
      netmask: 255.255.255.0
      gateway: 192.168.1.1
      dns1: 8.8.8.8
      dns2: 8.8.8.8
      device_type: vmxnet3
      iface: ens192
      iso_path: "[VCENTER_DATASTORE] ISO/rhel-8.3-x86_64-dvd.iso"
      vcenter_cluster: VCENTER_CLUSTER
      vcenter_datacenter: VCENTER_DATACENTER
      vcenter_network: VCENTER_PORTGROUP
      vcenter_guestid: rhel8_64Guest
      vcenter_folder: /
      validate_certs: no
...
